# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests. Using "/" is more efficient.
    schedule:
      interval: "weekly"
    # Allow updates only for packages matching this pattern
    allow:
      - dependency-name: "@privy-io/*"
    # For the allowed dependencies, ignore major version updates
    ignore:
      - dependency-name: "@privy-io/*"
        update-types: ["version-update:semver-major"]
